version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: menusappdb
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/menu.sql:/docker-entrypoint-initdb.d/menu.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d menuappdb"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      db_url: postgres://postgres:dev@db:5432/menusappdb?sslmode=disable
    ports:
      - "6969:6969"
volumes:
  pgdata:










