openapi: 3.1.0
info:
  title: Menus App
  description: API documentation for the Menus app
  version: 1.0.0
servers:
  - url: http://localhost:6969/

paths:

  /api/user:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    get:
      summary: Fetch all user accounts
      responses:
        '200':
          description: Successfully retrieved users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

  /api/user/{id}:
    get:
      summary: Fetch user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User account retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    patch:
      summary: Update user account by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: integer
                  example: 254
                email:
                  type: string
                  example: 'jd@dev.io'
                is_verified:
                  type: boolean
                  example: true
                contact_info:
                  $ref: '#/components/schemas/ContactInfo'
                settings:
                  $ref: '#/components/schemas/KeyValue'
      responses:
        '200':
          description: User account updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    delete:
      summary: Soft delete user account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User account deleted

  /api/business:
    post:
      summary: Create business
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Business'
      responses:
        '201':
          description: Business created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    get:
      summary: Fetch all businesses
      responses:
        '200':
          description: Businesses retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

  /api/business/{id}:
    get:
      summary: Fetch business by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Business retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'
        '404':
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    patch:
      summary: Update business by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Business'

    delete:
      summary: Soft delete business by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Business deleted
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'
        '404':
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

  /api/menu:

    get:
      description: Fetch all available menus
      responses:
        200:
          description: success, wrapped menus list in data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

        500:
          description: internal error, message wrapped in response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Menu'

  /api/menu/{menu_id}:
    get:
      description: 'fetch a menu given ID'
      responses:
        200:
          description: 'Success, menu wrapped in response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

        404:
          description: 'Missing menu, message wrapped'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'

    patch:
      description: 'Update menu with given ID'
      requestBody:
      responses:
        200:
          description: 'successful updated menu'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestBody'


    delete:
      description: 'Delete menu given ID'
      responses:
        204:
          description: 'deletion success'

  # Empty placeholders for other endpoints
  /api/list: { }
  /api/order: { }
  /api/notification: { }
  /api/review: { }
  /api/system: { }

components:
  schemas:

    gorm.Model:
      type: object
      properties:
        id:
          type: integer
        created_at:
          type: date-time
        updated_at:
          type: date-time
        deleted_at:
          type: date-time

    LatLng:
      type: object
      properties:
        lat:
          type: float
        lng:
          type: float

    ContactInfo:
      type: object
      properties:

        gorm.Model:
          $ref: '#/components/schemas/gorm.Model'

        location_name:
          type: string
        zip_code:
          type: string
        lat_lng:
          $ref: '#/components/schemas/LatLng'

    Business:
      type: object
      properties:

        id:
          type: integer

        name:
          type: string

        location:
          type: string

        contact_info:
          $ref: '#/components/schemas/ContactInfo'

        profile_id:
          type: integer

    Tag:
      type: string

    KeyValue:
      type: object
      properties:
        key:
          type: string
        value:
          type: object

    User:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        firebase_user_id:
          type: string

        phone:
          type: integer

        email:
          type: string

        is_verified:
          type: boolean

        contact_info:
          type: object
          $ref: '#/components/schemas/ContactInfo'

        settings:
          #          type: object
          $ref: '#/components/schemas/KeyValue'

        date_joined:
          type: date-time

        meta:
          #          type: object
          $ref: '#/components/schemas/Meta'

    Role:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        role_name:
          type: string

        code:
          type: string

        description:
          type: string

    Menu:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'
        title:
          type: string
        business_id:
          type: integer
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"

    MenuItems:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        contents:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'

        images:
          type: array
          items:
            type: string

        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'

        price:
          type: float

        unit_at:
          type: string

        unit_scale:
          type: string

        unit_symbol:
          type: string

        serving_type:
          type: string

        discounted:
          type: boolean

        total_kcal:
          type: float

        meta:
          type: object
          items:
            $ref: '#/components/schemas/KeyValue'

    DeliveryInfo:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        user_id:
          type: object
          $ref: '#/components/schemas/User'

        contact_info:
          type: object
          $ref: '#/components/schemas/ContactInfo'

        is_public:
          type: boolean

    Order:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        user_id:
          type: object
          $ref: '#/components/schemas/User'

        total:
          type: float

        discounted:
          type: boolean

        discounted_amount:
          type: float

        completed:
          type: boolean

        meta:
          type: object
          properties:
            KeyValue:
              type: object
              $ref: '#/components/schemas/KeyValue'

        delivery_info:
          type: object
          $ref: '#/components/schemas/DeliveryInfo'

    Meta:
      type: object
      properties:
        KeyValue:
          type: object
          $ref: '#/components/schemas/KeyValue'

    Review:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        contents:
          type: string

        star_rating:
          type: float

    OrderReview:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        order_id:
          type: object
          $ref: '#/components/schemas/Order'

        review_id:
          type: object
          $ref: '#/components/schemas/Review'

    List:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        name:
          type: string

        user_id:
          type: object
          $ref: '#/components/schemas/User'

        is_public:
          type: boolean

        meta:
          type: object
          $ref: '#/components/schemas/Meta'

    ListReview:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        list_id:
          type: object
          $ref: '#/components/schemas/List'

        review_id:
          type: object
          $ref: '#/components/schemas/Review'

        user_id:
          type: object
          $ref: '#/components/schemas/User'

    System:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        os:
          type: string

        server_id:
          type: string

    DeviceInfo:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        user_id:
          type: object
          $ref: '#/components/schemas/User'

        name:
          type: string

        model:
          type: string

        meta:
          type: object
          $ref: '#/components/schemas/Meta'

    AnalyticsEvent:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        event_name:
          type: string

        event_code:
          type: string

        event_for:
          type: string

    Analytics:
      type: object
      properties:
        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        device_info:
          type: object
          $ref: '#/components/schemas/DeviceInfo'

        event_code:
          type: object
          $ref: '#/components/schemas/AnalyticsEvent'

    NotificationChannel:
      type: object
      properties:

        gorm.Model:
          type: object
          $ref: '#/components/schemas/gorm.Model'

        channel_title:
          type: string

    NotificationSubscribers:
      type: object
      properties:

        user_id:
          type: object
          $ref: '#/components/schemas/User'

        channel_id:
          type: object
          $ref: '#/components/schemas/NotificationChannel'

    RequestBody:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        message:
          type: string